import type { Metadata } from "next";
import { archyedtBold, archyedtThin, firaGoRegular } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archyedtBold.variable} ${archyedtThin.variable} ${firaGoRegular.variable} font-archyedt-bold antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
